#!/bin/sh

DIFF_CMD='git diff --no-index'
XXD='xxd'

FILE_A="$1"
FILE_B="$2"
shift 2

FILE_A_TEMP="$(mktemp)"
FILE_B_TEMP="$(mktemp)"
trap "rm "$FILE_A_TEMP" "$FILE_B_TEMP"" EXIT INT HUP TERM

$XXD "$FILE_A" > "$FILE_A_TEMP"
$XXD "$FILE_B" > "$FILE_B_TEMP"

$DIFF_CMD "$FILE_A_TEMP" "$FILE_B_TEMP" $@

